---
title: "HubleyHW3"
author: "Claire Hubley"
date: "2023-03-24"
output: 
  html_notebook: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r libraries}
library(tidyverse)
library(tidyverse)
library(haven)
library(formatR)
library(Hmisc)
#install.packages("survey") 
library(survey)
#install.packages("srvyr")
#library(srvyr)
#install.packages("weights")
library(weights)
```
## Compile date and session info

```{r docinfo, echo = FALSE, warning= FALSE}

# print and get runtime ----
date()

# session info ----
sessionInfo()

```
## Step 1: Import and investigate datasets
```{r load, tidy = TRUE}

# Import data set in .csv format and create object(data.frame) titled "kenya_2009_df"

Zambia_HH_df <- read_csv(file = "C:\\Users\\ayoung1\\OneDrive\\Documents\\PhD\\TA\\IHSD 7440 HH sampling\\2023\\RStudio Lab\\2007_Zambia_HH_2023.csv")

Zambia_chld_df <- read_csv(file = "C:\\Users\\ayoung1\\OneDrive\\Documents\\PhD\\TA\\IHSD 7440 HH sampling\\2023\\RStudio Lab\\2007_Zambia_Child_2023.csv")

# View data set in new window
View(Zambia_HH_df)
View(Zambia_chld_df)

```

```{r rename}
View(Zambia_HH_2023 )
names(Zambia_HH_2023)
names(Zambia_HH_2023)[names(Zambia_HH_2023) == "HV022"] <- "Sample_stratum_number"
names(Zambia_HH_2023)[names(Zambia_HH_2023) == "HV023"] <- "Sample_domain"
names(Zambia_HH_2023)[names(Zambia_HH_2023) == "HV002"] <- "Household_number"
names(Zambia_HH_2023)[names(Zambia_HH_2023) == "HV005"] <- "Sample_weight"
names(Zambia_HH_2023)[names(Zambia_HH_2023) == "HV009"] <- "Number_HH_members"
names(Zambia_HH_2023)[names(Zambia_HH_2023) == "HV014"] <- "Number_children_5_under"
names(Zambia_HH_2023)[names(Zambia_HH_2023) == "HV021"] <- "Primary_sampling_unit"
names(Zambia_HH_2023)

describe(Zambia_HH_2023)
```

```{measure domains/units}
length(unique(Zambia_HH_2023$Primary_sampling_unit)) 
length(unique(Zambia_HH_2023$Sample_domain))
length(unique(Zambia_HH_2023$Household_number)) 

range=as.data.frame(table(Zambia_HH_2023$Primary_sampling_unit))

diff(range.default(range))

min(range$Freq)
max(range$Freq)

length(unique(Zambia_HH_2023$Sample_domain)) 

length(unique(Zambia_HH_2023$Sample_stratum_number)) 
```

```{set sample weight}
Zambia_HH_2023$porw = Zambia_HH_2023$Sample_weight/1000000
```

```{first attempt at res. table}
res_ITN <- table(Zambia_HH_2023$HH_residence, Zambia_HH_2023$HH_has_ITN)
prop.table(HH_has_ITN,1)
View (res_ITN)
```

```{better way with se}
Urban.ITN <- subset(Zambia_HH_2023, subset=(HH_residence=="Urban"))
attach(Urban.ITN)

Rural.ITN <- subset(Zambia_HH_2023, subset=(HH_residence=="Rural")) 
attach(Rural.ITN)


mean.urban <- mean(Urban.ITN$HH_has_ITN)
mean.urban 
se.urban <-sqrt(var(Urban.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(Urban.ITN$HH_has_ITN)))
se.urban

mean.rural <- mean(Rural.ITN$HH_has_ITN)
mean.rural 
se.rural <-sqrt(var(Rural.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(Rural.ITN$HH_has_ITN)))
se.rural
```

```{better way edu}
edu_ITN <- table(Zambia_HH_2023$HH_head_education,Zambia_HH_2023$HH_has_ITN) 
prop.table(edu_ITN,1)
edu_ITN

mean((Zambia_HH_2023$HH_head_education=="No education"))

Noedu.ITN <- subset(Zambia_HH_2023, subset=(HH_head_education=="No education"))
attach(Noedu.ITN)
Primary.ITN <- subset(Zambia_HH_2023, subset=(HH_head_education=="Primary"))
attach(Primary.ITN)
Secondary.ITN <- subset(Zambia_HH_2023, subset=(HH_head_education=="Secondary"))
attach(Secondary.ITN)
Higher.ITN <- subset(Zambia_HH_2023, subset=(HH_head_education=="Higher than"))
attach(Higher.ITN)

View(Noedu_ITN)

mean.none <- mean(Noedu.ITN$HH_has_ITN) #No education
mean.none
se.none <-sqrt(var(Noedu.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(Noedu.ITN$HH_has_ITN)))
se.none
mean.primary<- mean(Primary.ITN$HH_has_ITN)#Primary
mean.primary
se.primary <-sqrt(var(Primary.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(Primary.ITN$HH_has_ITN)))
se.primary
mean.secondary<- mean(Secondary.ITN$HH_has_ITN)#Secondary
mean.secondary
se.secondary <-sqrt(var(Secondary.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(Secondary.ITN$HH_has_ITN)))
se.secondary
mean.higher <- mean(Higher.ITN$HH_has_ITN)#Higher than
mean.higher
se.higher <-sqrt(var(Higher.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(Higher.ITN$HH_has_ITN)))
se.higher
```

```{better way SES}
lowestSES.ITN <- subset(Zambia_HH_2023, subset=(HH_wealth_index=="Lowest"))
attach(lowestSES.ITN)
lowSES.ITN <- subset(Zambia_HH_2023, subset=(HH_wealth_index=="Fourth"))
attach(lowSES.ITN)
middleSES.ITN <- subset(Zambia_HH_2023, subset=(HH_wealth_index=="Middle"))
attach(middleSES.ITN)
richSES.ITN <- subset(Zambia_HH_2023, subset=(HH_wealth_index=="Second"))
attach(richSES.ITN)
richestSES.ITN <- subset(Zambia_HH_2023, subset=(HH_wealth_index=="Highes"))
attach(richestSES.ITN)

mean.lowest <- mean(lowestSES.ITN$HH_has_ITN)
mean.lowest
se.lowest <-sqrt(var(lowestSES.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(lowestSES.ITN$HH_has_ITN)))
se.lowest
mean.low<- mean(lowSES.ITN$HH_has_ITN)
mean.low
se.low <-sqrt(var(lowSES.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(lowSES.ITN$HH_has_ITN)))
se.low
mean.middle<- mean(middleSES.ITN$HH_has_ITN)
mean.middle
se.middle <-sqrt(var(middleSES.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(middleSES.ITN$HH_has_ITN)))
se.middle
mean.rich <- mean(richSES.ITN$HH_has_ITN)
mean.rich
se.rich <-sqrt(var(richSES.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(richSES.ITN$HH_has_ITN)))
se.rich
mean.richest <- mean(richestSES.ITN$HH_has_ITN)
mean.richest
se.richest <-sqrt(var(richestSES.ITN$HH_has_ITN,na.rm=TRUE)/length(na.omit(richestSES.ITN$HH_has_ITN)))
se.richest
```

```{first try with weighted}
ITN_urban_m <- weighted.mean(Urban.ITN$HH_has_ITN, Urban.ITN$porw, na.rm=TRUE)
ITN_urban_m
ITN_rural_m <- weighted.mean(Rural.ITN$HH_has_ITN, Rural.ITN$porw, na.rm=TRUE)
ITN_rural_m

dim(Urban.ITN)
dim(Rural.ITN)

```

```{make weighted function}
DHSs_SRS_wtd<-svydesign(ids= ~1, weights=~porw, data=Zambia_HH_2023, nest=TRUE)
```

```{weighted SRS res}
ITN.Res.SRS <- svyby(~HH_has_ITN, ~HH_residence, DHSs_SRS_wtd, svymean, na.rm=TRUE) #Residence
ITN.Res.SRS
```

```{make cluster function and cluster res}
DHS_Clstr_wtd<-svydesign(ids= ~Primary_sampling_unit, weights=~porw, data=Zambia_HH_2023, nest=TRUE)

ITN.Res.Clstr <- svyby(~HH_has_ITN, ~HH_residence, DHS_Clstr_wtd, svymean, na.rm=TRUE) #Residence
ITN.Res.Clstr
```


```{cluster edu}
ITN.Edu.Clstr<- svyby(~HH_has_ITN, ~HH_head_education, DHS_Clstr_wtd, svymean, na.rm=TRUE)
ITN.Edu.Clstr
```

```{cluster and SRS weighted SES}
ITN.SES.SRS<- svyby(~HH_has_ITN, ~HH_wealth_index, DHSs_SRS_wtd, svymean, na.rm=TRUE)
ITN.SES.SRS

ITN.SES.Clstr<- svyby(~HH_has_ITN, ~HH_wealth_index, DHS_Clstr_wtd, svymean, na.rm=TRUE)
ITN.SES.Clstr
```

```{stratified cluster function}
DHS_Clstr_strat <-svydesign(ids= ~Primary_sampling_unit, strata= ~Sample_stratum_number, weights=~porw,data=Zambia_HH_2023, nest=TRUE)
```

```{all measures stratified}
ITN.Res.Strat <- svyby(~HH_has_ITN, ~HH_residence, DHS_Clstr_strat, svymean, na.rm=TRUE) #Residence
ITN.Res.Strat

ITN.SES.Strat <- svyby(~HH_has_ITN, ~HH_head_education, DHS_Clstr_strat, svymean, na.rm=TRUE) 
ITN.SES.Strat

ITN.edu.Strat <- svyby(~HH_has_ITN, ~HH_head_education, DHS_Clstr_strat, svymean, na.rm=TRUE) 
ITN.edu.Strat
```

```{read in child csv}
zambia_child<-read.csv(file ="/Users/ClaireHubley/Documents/IHSDrstudio/IHSD_7440_HH_Sampling/2007_Zambia_Child_2023.csv")
View(zambia_child)
```


```{rename, set weights, and describe child set}
names(zambia_child)
names(zambia_child)[names(zambia_child) == "V022"] <- "Sample_stratum_number"
names(zambia_child)[names(zambia_child) == "V023"] <- "Sample_domain"
names(zambia_child)[names(zambia_child) == "V002"] <- "Household_number"
names(zambia_child)[names(zambia_child) == "V005"] <- "Sample_weight"
names(zambia_child)[names(zambia_child) == "V021"] <- "Primary_sampling_unit"
names(zambia_child)

library(Hmisc)

length(unique(zambia_child$Primary_sampling_unit)) 
describe(zambia_child)

zambia_child$porw = zambia_child$Sample_weight/1000000
```

```{SRS child all measures}
res.ch_ITN <- table(zambia_child$HH_residence, zambia_child$Slept_ITN)
prop.table(res.ch_ITN,1)
View (res.ch_ITN)

Urban.chITN <- subset(zambia_child, subset=(HH_residence=="Urban"))
attach(Urban.ITN)

Rural.chITN <- subset(zambia_child, subset=(HH_residence=="Rural")) 
attach(Rural.chITN)

mean.churban <- mean(Urban.chITN$Slept_ITN)
mean.churban
se.churban <-sqrt(var(Urban.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(Urban.chITN$Slept_ITN)))
se.churban

mean.chrural <- mean(Rural.chITN$Slept_ITN)
mean.chrural 
se.chrural <-sqrt(var(Rural.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(Rural.chITN$Slept_ITN)))
se.chrural

zero.chITN <- subset(zambia_child, subset=(Child_age==0))
attach(zero.chITN)

one.chITN <- subset(zambia_child, subset=(Child_age==1)) 
attach(one.chITN)

two.chITN <- subset(zambia_child, subset=(Child_age==2)) 
attach(two.chITN)

three.chITN <- subset(zambia_child, subset=(Child_age==3)) 
attach(three.chITN)

four.chITN <- subset(zambia_child, subset=(Child_age==4)) 
attach(four.chITN)

mean.ch.zero <- mean(zero.chITN$Slept_ITN)
mean.ch.zero 
se.ch.zero <-sqrt(var(zero.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(zero.chITN$Slept_ITN)))
se.ch.zero 

mean.ch.one <- mean(one.chITN$Slept_ITN)
mean.ch.one 
se.ch.one <-sqrt(var(one.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(one.chITN$Slept_ITN)))
se.ch.one 

mean.ch.two <- mean(two.chITN$Slept_ITN)
mean.ch.two 
se.ch.two <-sqrt(var(two.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(two.chITN$Slept_ITN)))
se.ch.two 

mean.ch.three <- mean(three.chITN$Slept_ITN)
mean.ch.three 
se.ch.three <-sqrt(var(three.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(three.chITN$Slept_ITN)))
se.ch.three 

mean.ch.four <- mean(four.chITN$Slept_ITN)
mean.ch.four 
se.ch.four <-sqrt(var(four.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(four.chITN$Slept_ITN)))
se.ch.four 

poorest.chITN <- subset(zambia_child, subset=(HH_wealth_index=="Lowest")) 
attach(poorest.chITN)

poor.chITN <- subset(zambia_child, subset=(HH_wealth_index=="Fourth")) 
attach(poor.chITN)

middle.chITN <- subset(zambia_child, subset=(HH_wealth_index=="Middle")) 
attach(middle.chITN)

rich.chITN <- subset(zambia_child, subset=(HH_wealth_index=="Second")) 
attach(rich.chITN)

richest.chITN <- subset(zambia_child, subset=(HH_wealth_index=="Highes")) 
attach(richest.chITN)

mean.ch.lowest <- mean(poorest.chITN$Slept_ITN)
mean.ch.lowest 
se.ch.lowest <-sqrt(var(poorest.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(poorest.chITN$Slept_ITN)))
se.ch.lowest 

mean.ch.low <- mean(poor.chITN$Slept_ITN)
mean.ch.low 
se.ch.low <-sqrt(var(poor.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(poor.chITN$Slept_ITN)))
se.ch.low 

mean.ch.middle <- mean(middle.chITN$Slept_ITN)
mean.ch.middle 
se.ch.middle <-sqrt(var(middle.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(middle.chITN$Slept_ITN)))
se.ch.middle 

mean.ch.rich <- mean(rich.chITN$Slept_ITN)
mean.ch.rich 
se.ch.rich <-sqrt(var(rich.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(rich.chITN$Slept_ITN)))
se.ch.rich 

mean.ch.richest <- mean(richest.chITN$Slept_ITN)#
mean.ch.richest 
se.ch.richest <-sqrt(var(richest.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(richest.chITN$Slept_ITN)))
se.ch.richest 

noedu.chITN <- subset(zambia_child, subset=(Mother_education=="No education")) 
attach(noedu.chITN)

predu.chITN <- subset(zambia_child, subset=(Mother_education=="Primary")) 
attach(predu.chITN)

seedu.chITN <- subset(zambia_child, subset=(Mother_education=="Secondary")) 
attach(seedu.chITN)

htedu.chITN <- subset(zambia_child, subset=(Mother_education=="Higher than")) 
attach(htedu.chITN)

mean.ch.noedu <- mean(noedu.chITN$Slept_ITN)
mean.ch.noedu 
se.ch.noedu <-sqrt(var(noedu.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(noedu.chITN$Slept_ITN)))
se.ch.noedu 

mean.ch.predu <- mean(predu.chITN$Slept_ITN)
mean.ch.predu 
se.ch.predu <-sqrt(var(predu.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(predu.chITN$Slept_ITN)))
se.ch.predu 

mean.ch.seedu <- mean(seedu.chITN$Slept_ITN)
mean.ch.seedu 
se.ch.seedu <-sqrt(var(seedu.chITN$Slept_ITN,na.rm=TRUE)/length(na.omit(seedu.chITN$Slept_ITN)))
se.ch.seedu 

ITN_urban_chm <- weighted.mean(Urban.chITN$Slept_ITN, Urban.chITN$porw, na.rm=TRUE)
ITN_urban_chm
ITN_rural_chm <- weighted.mean(Rural.chITN$Slept_ITN, Rural.chITN$porw, na.rm=TRUE)
ITN_rural_chm

DHSs_SRS_wtd<-svydesign(ids= ~1, weights=~porw, data=zambia_child, nest=TRUE)

ITN.chRes.SRS <- svyby(~Slept_ITN, ~HH_residence, DHSs_SRS_wtd, svymean, na.rm=TRUE) 
ITN.chRes.SRS

DHS_chClstr_wtd<-svydesign(ids= ~Primary_sampling_unit, weights=~porw, data=zambia_child, nest=TRUE)

ITN.chRes.Clstr <- svyby(~Slept_ITN, ~HH_residence, DHS_chClstr_wtd, svymean, na.rm=TRUE) 
ITN.chRes.Clstr

DHS_chClstr_strat <-svydesign(ids= ~Primary_sampling_unit, strata= ~Sample_stratum_number, weights=~porw,data=zambia_child, nest=TRUE)

ITN.chRes.Strat <- svyby(~Slept_ITN, ~HH_residence, DHS_chClstr_strat, svymean, na.rm=TRUE) 
ITN.chRes.Strat

ITN_zero_chm <- weighted.mean(zero.chITN$Slept_ITN, zero.chITN$porw, na.rm=TRUE)
ITN_zero_chm
ITN_one_chm <- weighted.mean(one.chITN$Slept_ITN, one.chITN$porw, na.rm=TRUE)
ITN_one_chm

ITN.chage.SRS <- svyby(~Slept_ITN, ~Child_age, DHSs_SRS_wtd, svymean, na.rm=TRUE)
ITN.chage.SRS

ITN.chSES.SRS <- svyby(~Slept_ITN, ~HH_wealth_index, DHSs_SRS_wtd, svymean, na.rm=TRUE)
ITN.chSES.SRS

ITN.chedu.SRS <- svyby(~Slept_ITN, ~Mother_education, DHSs_SRS_wtd, svymean, na.rm=TRUE)
ITN.chedu.SRS

DHS_chClstr_wtd<-svydesign(ids= ~Primary_sampling_unit, weights=~porw, data=zambia_child, nest=TRUE)

ITN.chage.Clstr <- svyby(~Slept_ITN, ~Child_age, DHS_chClstr_wtd, svymean, na.rm=TRUE) 
ITN.chage.Clstr

ITN.chSES.Clstr <- svyby(~Slept_ITN, ~HH_wealth_index, DHS_chClstr_wtd, svymean, na.rm=TRUE) 
ITN.chSES.Clstr

ITN.chedu.Clstr <- svyby(~Slept_ITN, ~Mother_education, DHS_chClstr_wtd, svymean, na.rm=TRUE) 
ITN.chedu.Clstr

ITN.chage.Strat <- svyby(~Slept_ITN, ~Child_age, DHS_chClstr_strat, svymean, na.rm=TRUE) 
ITN.chage.Strat

ITN.chSES.Strat <- svyby(~Slept_ITN, ~HH_wealth_index, DHS_chClstr_strat, svymean, na.rm=TRUE) 
ITN.chSES.Strat

ITN.chedu.Strat <- svyby(~Slept_ITN, ~Mother_education, DHS_chClstr_strat, svymean, na.rm=TRUE) 
ITN.chedu.Strat
``` 

```{retrying 1d and 1e}
length(unique(Zambia_HH_2023$Sample_stratum_number))
length(unique(Zambia_HH_2023$Sample_domain))
```

length(unique(Zambia_HH_2023$Sample_domain))